### ISSUE TITLE
SD Card Menu option causes unhandled exception.

### ISSUE THREAD

**Issue by bonjipoo** [VoronDesign/Voron-Hardware#100]
Ive fresh installed Klipper on a new printer and all is working.  Configured a V0 display for it which is also working however when trying to use the SD Card menu option I get an unhandled exception.  See log and screenshot.  

[klippy-12.log](https://github.com/VoronDesign/Voron-Hardware/files/7316089/klippy-12.log

<img width="604" alt="Screenshot 2021-10-09 at 18 39 22" src="https://user-images.githubusercontent.com/5507101/136669060-8cfbad48-9954-4030-ac22-5b6eb8d50f81.png">
)

**Comment by timmit99** [comment]
That error is a klipper module error and nothing to do with the display.
