### ISSUE TITLE
Issue flashing via USB

### ISSUE THREAD

**Issue by E-Olsen** [VoronDesign/Voron-Hardware#106]
I followed the instructions to flash to match the current Klipper version and got the following output:

  Flashing out/klipper.bin to 0483:df11
sudo dfu-util -d ,0483:df11 -R -a 0 -s 0x8000000:leave -D out/klipper.bin

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available

Failed to flash to 0483:df11: Error running dfu-util

If the device is already in bootloader mode it can be flashed with the
following command:
  make flash FLASH_DEVICE=0483:df11
  OR
  make flash FLASH_DEVICE=1209:beba

If attempting to flash via 3.3V serial, then use:
  make serialflash FLASH_DEVICE=0483:df11

make: *** [src/stm32/Makefile:75: flash] Error 255

**Comment by timmit99** [comment]
@E-Olsen sorry for the late reply, dont normally do help on github!

Have you put the boot jumper onto the board and verified that it *is* in DFU mode and that the device ID is correct?

**Comment by E-Olsen** [comment]
Oops, forgot to close this.  Since my install was not live in a printer yet I wiped it from the RPi and rebuilt.  That let me flash it successfully.  User error, this can be closed.
