### ISSUE TITLE
MAX31865 PT100 Guide rtd_reference_r: 400 instead of 430

### ISSUE THREAD

**Issue by sprior** [VoronDesign/Voron-Hardware#110]
It seems that while rtd_reference_r: 430 might have been correct for SKR boards, the correct value seems to be closer to 400 for the Spyder and Octopus boards people are using today.

I set up my Voron 2.4 with a PT100 stick with a Spyder board and ended up troubleshooting extruder clicking with the documented settings.  Only when I decided the issue was lower than reported extruder temp did I find out the rtd_reference_r config should be 400 instead of 430.

**Comment by raymondh2** [comment]
This varies based on the PCB itself. The config included is just an example
