### ISSUE TITLE
Scrolling options

### ISSUE THREAD

**Issue by scynthero** [VoronDesign/Voron-Hardware#115]
Hi!
Regarding voron v0 display mod.
Is there a possibility to add settings like so:
right (clockwise) scrolls up or increases values. Left (counter-clockwise) scrolls down or decreases values?
Thanks for the mod ^^

**Comment by raymondh2** [comment]
Swap the two pins in the config https://github.com/VoronDesign/Voron-Hardware/blob/master/V0_Display/Software/V0Display.cfg#L12
