### ISSUE TITLE
Will the LDO in V0_PCB_Mod/Hotend_PCB too hot?

### ISSUE THREAD

**Issue by kaidegit** [VoronDesign/Voron-Hardware#116]
When using a 24V power and a 5V fan, the current throught LDO may up to 100mA and the thermal power will up to about 2W. It will too hot that the LDO may cannot bear.

**Comment by timmit99** [comment]
@JNP-1 any notes on this?

**Comment by JNP-1** [comment]
I have not had any problems with it but you can stick a small heat sink on the LDO and keep the temperature low.
