### ISSUE TITLE
STEP file for V0 display assembly is corrupted

### ISSUE THREAD

**Issue by austinvojta** [VoronDesign/Voron-Hardware#130]
https://github.com/VoronDesign/Voron-Hardware/blob/master/V0_Display/CAD/V0_Display_Assembly.step

Won't open in Fusion 360 (but other STEPs from this repo open fine). Gives error message as screenshotted below.

![image](https://user-images.githubusercontent.com/36388567/153451546-afe37e79-5741-4b52-9fc8-08c65cb17e0f.png)

**Comment by raymondh2** [comment]
@timmit99 I have verified this.

**Comment by raymondh2** [comment]
Should be fixed in #142
