### ISSUE TITLE
Klipper Expander - Possible to remove pullup from PA6 & PA5?

### ISSUE THREAD

**Issue by gargamel778** [VoronDesign/Voron-Hardware#155]
Hi,

I have just installed Klipper Expander board to control 2x heavy duty PWM fans (using mosfet0 and mosfet1), which works fine.

I would like to use T0 & T1 (pins PA6 / PA5 respectively) for the fans' tachometer pin. I've added the following lines to the relevant fan configuration section in my printer.cfg -  
`tachometer_pin: expander:PA6` (for fan1) / `tachometer_pin: expander:PA5` (for fan2)
`tachometer_ppr: 2`

With one of the fans I'm getting erroneous readings on the dashboard, such as ~700RPM when the fan is off, whereas with the second fan I'm not getting any readings at all. 
However, when I connect one of the fan's tachometer pin to the GPIO of the Expander board (pin PA7) and configure it accordingly (`tachometer_pin: expander:PA7`), the fan speed is reported correctly. 
Unfortunately, there's only one GPIO, so I am able to get correct readings from only one of the fans.

Is it possible to remote the pullup resistors from the board, so that T0/T1 (MCU ping PA6 & PA5) will behave similarly to the PA7 GPIO? I don't intend to use these inputs for thermistors and therefore don't mind performing hardware changes (if possible at all).

**Comment by raymondh2** [comment]
You don't want to use a controller that uses PWM on the negative rail of fans and measure the tach signal. It will create a signal that won't make sense. (floating ground)
