### ISSUE TITLE
typo in the commands for firmware flashing?

### ISSUE THREAD

**Issue by PMvE** [VoronDesign/Voron-Hardware#159]
it looks like there is a typo in the klipper expander instalation guide under Setup it says to use 
"CD ~/klipper"
to go to the klipper directory it returns 
"-bash: CD: command not found" 
in the voron documentation it says 
"cd ~/klipper" 
that one works. i am really bad with this stuff so i might be wrong.

**Comment by raymondh2** [comment]
@timmit99

**Comment by timmit99** [comment]
Yep, I sword I had fixed that.... Something must have reverted it.
@PMvE do you know how to make a pull request? Imm away from my PC for a bit so I can't fix it right away.

**Comment by PMvE** [comment]
i think google can help me with that and i should learn it anyway

**Comment by PMvE** [comment]
https://github.com/VoronDesign/Voron-Hardware/pull/160 I think i did it wrong sorry

**Comment by timmit99** [comment]
@PMvE looks good to me.

@raymondh2 thoughts?
