### ISSUE TITLE
0.2 version of PCB mount sets PCB too low

### ISSUE THREAD

**Issue by EricZimmerman** [VoronDesign/Voron-Hardware#193]
This part:

https://github.com/VoronDesign/Voron-Hardware/blob/master/V0-Umbilical/STLs/V0.2/V0.2_Toolhead_PCB_Mount.STL

has minimal clearance with the BA motor mounts in the back. seems like the pcb should be moved up as far as allows for hole spacing to provide more clearance with mounts

**Comment by EricZimmerman** [comment]
https://discord.com/channels/460117602945990666/710952853514223617/1068596392966230178

**Comment by kejar31** [comment]
I believe this was resolved with my update, correct ?

**Comment by Gabbajoe** [comment]
Hi no for me it is stil la issue that the [V0.2_Toolhead_PCB_Mount.STL](https://github.com/VoronDesign/Voron-Hardware/blob/master/V0-Umbilical/STLs/V0.2/V0.2_Toolhead_PCB_Mount.STL) is not clearing the A/B Motor upper frames see:
![image](https://user-images.githubusercontent.com/5196156/227041365-fac9eb09-b6b4-46df-bc23-5ee2622fcbb6.png)

I did now the lazy way an shave off in an angle plastic unter the screw holes.

**Comment by i8086m** [comment]
Having same issue with [V0.2_Toolhead_PCB_Mount.STL](https://github.com/VoronDesign/Voron-Hardware/blob/master/V0-Umbilical/STLs/V0.2/V0.2_Toolhead_PCB_Mount.STL) colliding

![PXL_20230330_163231354](https://user-images.githubusercontent.com/35865583/228906001-b33d43a0-4775-4f6e-9579-cb26af8476fd.jpg)

**Comment by tkalbitz** [comment]
Had the same issue and shaved also the screw feature off.
