### ISSUE TITLE
V0 display random disconnect 

### ISSUE THREAD

**Issue by yzheka** [VoronDesign/Voron-Hardware#198]
I have issue with v0 display. It shuts down random in few hours. Klipper says that lost connection to mcu. Display keeps showing progress and time but encoder doesn't respond. It happens always after few hours of printer turned on. To fix display I can press reset button on it and restart klipper.

**Comment by raymondh2** [comment]
Hi! For troubleshooting help please visit one of our other platforms. We keep github issues open for design issues. 

https://vorondesign.com/

**Comment by timmit99** [comment]
> 

Really sounds like a bad USB cable

**Comment by yzheka** [comment]
I have changed 2 or 3 of them. In the last try I have soldered it directly to the pins on the display
