### ISSUE TITLE
STL/STEP files for Daylight/Disco Stick 1515 brackets do not work

### ISSUE THREAD

**Issue by pdsavas** [VoronDesign/Voron-Hardware#201]
I just downloaded the STEP and STL files for the 1515 brackets and tried to open them with several different applications, but the files appear to be corrupt. Would someone be able to correct this and reupload working copies, please?

Thanks,
pete

**Comment by BerzerkaDurk** [comment]
Guessing you just pressed the download button in the STL folder. Instead, right-click the button and choose "save link as" or "save target as", depending on your browser.

**Comment by pdsavas** [comment]
No, I actually did right-click and try to save the files using the "save target as," and they always came down corrupted. I couldn't get any slicer or 3D modeling program to open them.

**Comment by timmit99** [comment]
Can you upload one of those files here for us to check?

Thanks!

**Comment by pdsavas** [comment]
[Brackets_1515_x2.zip](https://github.com/VoronDesign/Voron-Hardware/files/11166162/Brackets_1515_x2.zip)
There you go.

pete

**Comment by timmit99** [comment]
> [Brackets_1515_x2.zip](https://github.com/VoronDesign/Voron-Hardware/files/11166162/Brackets_1515_x2.zip) There you go.
> 
> pete

You downloaded the webpage, not the STL file.
![image](https://user-images.githubusercontent.com/8399317/230270074-94a3af0a-f94d-48d7-83af-c12a91b5e940.png)

**Comment by timmit99** [comment]
"Save link as" is what you want here.
![image](https://user-images.githubusercontent.com/8399317/230270169-bd548cea-1f87-4522-b3c9-ffa6434044cb.png)



That gives me this file which works:
![image](https://user-images.githubusercontent.com/8399317/230270205-5af611ce-4b8e-4e0c-9600-796f83350dd0.png)

**Comment by pdsavas** [comment]
I swear that's what I did... (sigh). Thanks, and sorry.

**Comment by BerzerkaDurk** [comment]
Called it. :o)
99/100 times when someone downloads a corrupt STL from the repo, that's it.

**Comment by pepegragera** [comment]
The files are corrupted, does anyone have them? the links that you have put are downloaded but when uploading to the laminator it says that it is corrupt
