### ISSUE TITLE
V0_Display ROM too small for latest klipper firmware

### ISSUE THREAD

**Issue by alidaf** [VoronDesign/Voron-Hardware#206]
Klipper version v0.11.0-219-g645a1b83
Trying to flash results in 
/usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: out/klipper.elf section `.text' will not fit in region `rom'
/usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: region `rom' overflowed by 242 bytes
collect2: error: ld returned 1 exit status

**Comment by SaltyPaws** [comment]
For me this worked:
https://klipper.discourse.group/t/mcu-protocol-error-on-update-to-klipper-v0-11-0-226-g0245073c/9024

**Comment by timmit99** [comment]
This had been fixed in the latest klipper update! I've updated the flashing instructions to show what to change to get it to fit!

**Comment by SaltyPaws** [comment]
Please check the checkmarks for enabled sections. For me what is currently shown in your instruction on github does not work as you need I2C. The screenshot that I posted is different and does work.
