### ISSUE TITLE
No BOM for STM32_Mini12864

### ISSUE THREAD

**Issue by bigjoe4265** [VoronDesign/Voron-Hardware#65]
There appears to be no BOM to assemble this board.

**Comment by royalevo9** [comment]
R1, R2, R3  SMD 0805 resistor  10K  
R4 SMD 0805 resistor 1K
U1  STM32F042F6P6  
C1, C4 SMD 0805 MLCC capacitor 4.7uF 25V
C2, C3 SMD 0805 MLCC capacitor 0.1uF 25V
U2 AP2127K-3.3TRG1  SOT23-5
U3 74LVC1G17GV SOT-753
D1 LED SMD 0805 diode RED
J1 Micro USB connector B type MOLEX 1050170001
J2 2P Header male P=2.54
J3 3P Header male P=2.54
SW1 Tactile switch 6*3.5*4.3 SKHLACA010
EXP1, EXP2  Female HEADER 2*5P P=2.54mm SMD [https://www.aliexpress.com/item/32838196161.html](url)

**Comment by raymondh2** [comment]
#68
