### ISSUE TITLE
Remove JLC text from Microswitch_endstop B.silks

### ISSUE THREAD

**Issue by bigjoe4265** [VoronDesign/Voron-Hardware#72]
Remove JLCJLCJLCJLC text from MicroswitchXY-Endstop.kicad_pcb file

  (gr_text JLCJLCJLCJLC (at 167.6 68.4) (layer B.SilkS)
    (effects (font (size 1 1) (thickness 0.15)) (justify mirror))
  )

**Comment by raymondh2** [comment]
@randellhodges

**Comment by timmit99** [comment]
@bigjoe4265 that line is there so when the board is ordered from JLC, they out the order number there so it's in a known location. 
If the original designer wants to remove it that's fine, but its a nice addition for making boards.

**Comment by bigjoe4265** [comment]
> 
> 
> @bigjoe4265 that line is there so when the board is ordered from JLC, they out the order number there so it's in a known location.
> If the original designer wants to remove it that's fine, but its a nice addition for making boards.

that's great, but what if I wish to to use another pcb manufactorer?

**Comment by raymondh2** [comment]
Like timmit suggested you can remove it yourself.

**Comment by bigjoe4265** [comment]
> 
> 
> Like timmit suggested you can remove it yourself.

I'm not that familiar with KiCad.  I tried that approach and can't get it to update the files properly.

**Comment by timmit99** [comment]
@bigjoe4265 let me make a version without the jlc text. Do you want me to screen capture to show you how? Any interest in learning kicad basics?

**Comment by bigjoe4265** [comment]
Yes, but I don't want to clutter up the reported issues here.  I was able to update the schematic file however it's saying I'm missing libraries when I try to update pcb.

**Comment by timmit99** [comment]
Let me take a look and report back!

**Comment by timmit99** [comment]
@bigjoe4265 here's what i was able to do.
https://youtu.be/DSm7_0XXC-4

[Gerbers_No_JLC.zip](https://github.com/VoronDesign/Voron-Hardware/files/6096488/Gerbers_No_JLC.zip)

**Comment by bigjoe4265** [comment]
Thank you for the assistance and the tutorial.
