### ISSUE TITLE
Taco Raven BOM HTML

### ISSUE THREAD

**Issue by Kosh42** [VoronDesign/Voron-Hardware#76]
![Screenshot_20210402-093529](https://user-images.githubusercontent.com/58401509/113398649-da31b400-9396-11eb-8872-48f3a1d68295.png)
The link appears to be broken.

**Comment by Fleafa** [comment]
Is: http://htmlpreview.github.io/?https://github.com/VoronDesign/Voron-Hardware/blob/V0-Micro/V0_Micro_Display/InteractiveBOM.html
Should be: http://htmlpreview.github.io/?https://github.com/VoronDesign/Voron-Hardware/blob/master/V0_Micro_Display/InteractiveBOM.html

**Comment by FHeilmann** [comment]
Fixed by #86
