### ISSUE TITLE
Very minor documentation change.

### ISSUE THREAD

**Issue by monsterguy** [VoronDesign/Voron-Hardware#93]
https://github.com/VoronDesign/Voron-Hardware/blob/master/V0_Display/Documentation/Setup_and_Flashing_Guide.md

Contains the line "USB ids --->[ ] Specify a custom step pulse duration"

It should be split into two lines 

"USB ids --->"
"[ ] Specify a custom step pulse duration"

It tripped Nero up on his stream, so I imagine other people may be confused by that as well.

**Comment by Kosh42** [comment]
See PR 95: https://github.com/VoronDesign/Voron-Hardware/pull/95#issue-717135143
